### ISSUE TITLE
Unrecognized field zeroVector when using Wordspace

### ISSUE THREAD

**Issue by gbarlacchi** [SAG-KeLP/kelp-core#3]
Hi,
I'm experimenting with SPTK and I'm having the following issue when I load a saved model.

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "zeroVector"

I noticed that in WordspaceI there is only the method getZeroVector and it doesn't have @Jsonignore. Could be here the problem? Adding this annotation solves the problem, but I don't if the something else is then affected. 
Thanks!

**Comment by SimoneFilice** [comment]
Hi Gianni,

Thanks for using KeLP and for let us know this bug. Your solution is actually correct, I already modified the development branch of KeLP.

Best,
Simone
