### ISSUE TITLE
Meta-learning via Random Search for classifiers from another Java library

### ISSUE THREAD

**Issue by okonechn** [SAG-KeLP/kelp-core#4]
Does KeLP do the hyperparameter optimization via e.g. Random Search or another similar approach?
If so, does it able to take classifiers from another Java library to run meta-learning?
Can you please provide some code examples?

**Comment by SimoneFilice** [comment]
Hi,

Thanks for using KeLP. We currently do not support any hyperparameter optimization technique. Is there any specific Java library you recommend to interface with?

Thanks,
Simone
