### ISSUE TITLE
Upgrade of jackson-databind dependency

### ISSUE THREAD

**Issue by DoctorNypar** [SAG-KeLP/kelp-core#5]
Hi,
I'd like to include kelp-core in my project but I have some troubles with jackson-databind dependency: my project uses spring-boot 2.0.2 which imports jackson-databind 2.9.5, but kelp-core doesn't work with that version (some methods required in kelp-core are missing in latest versions of jackson-databind). Can you upgrade the jackson-databind dependency to a higher version? I've noticed that there is also a pull request about this topic.
Thank you

**Comment by SimoneFilice** [comment]
Hi,

Thanks for using KeLP. As you know, updating to the new Jackson dependency is not straightforward, as they significantly changed many methods. 
The pull request we had is very old, and cannot be used right now. 
We do not plan to make this change in the immediate future, but if you would like to do it we will be happy to review and accept your pull request and I am sure the entire community will benefit.

Thanks,
Simone

**Comment by crux82** [comment]
Hi all,

the dependency com.fasterxml.jackson.core:jackson-databind is upgrated to version 2.9.10.3 as suggester by GitHub.

Bests 

Danilo
